name: Module 5 - Extract Integration Package

on:
  workflow_dispatch:
    inputs:
      artifactName:
        description: "Artifact Name"
        required: true
        default: "integration-package"

jobs:
  extract:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.event.inputs.artifactName }}
          path: downloads

      - name: Show Downloaded Files
        run: |
          echo "Downloaded files:"
          ls -R downloads

      - name: Install unzip
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip

      - name: Extract ZIP
        run: |

          mkdir extracted

          ZIP=$(find downloads -name "*.zip")

          echo "ZIP Found:"
          echo "$ZIP"

          unzip "$ZIP" -d extracted

      - name: Show Extracted Content
        run: |
          echo "Extracted structure:"
          ls -R extracted

      - name: Read Export Metadata
        run: |

          echo "Export Information"

          find extracted -type f

          echo ""

          echo "contentmetadata"

          if [ -f extracted/contentmetadata ]; then
            cat extracted/contentmetadata
          fi

          echo ""

          echo "ExportInformation.info"

          if [ -f extracted/ExportInformation.info ]; then
            cat extracted/ExportInformation.info
          fi
